apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --out chart
    kompose.version: 1.16.0 (HEAD)
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  creationTimestamp: null
  labels:
    io.kompose.service: openeducat11
  name: openeducat11
spec:
  type: LoadBalancer
  ports:
    - name: "8069"
      port: 8069
      targetPort: 8069
    - name: "8071"
      port: 8071
      targetPort: 8071
  selector:
    io.kompose.service: openeducat11
status:
  loadBalancer: {}
